# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1777b7e8af2863a36a92daffd4f9d89cd0af47bd03ca950b16687392e5ef689dd076adf78b67c0b1bb81e12eb35462593ce7f61d5a6a898a3c81a7a7937033fe

test:
  secret_key_base: 2a534a8e20d856ccd7fd4f093288090c85646b64f508dfa0688c1065aa248858e766e97b01714ee336e2d7d88b60f40d2f1d2964bdff2927bac36ecc311f05d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
